*Part 2: Python for Data Analysis II*
### Working with Pandas###
#Exercises#



---


<font color='violet'>
Hints are written in white, so you do not see them immediately. If you highlight them (or double-click on them), they will appear! 
<font color='white'> I am a hint! :-)


---

In [ ]:
# Your feedback: If you have any suggestions about the course or the excercises, 
# you can provide them here!

## 1. Basic exercises

### Data inspection

**1.1.** Import the pandas and the numpy library:

**1.2.** In the following folder you will find a dataset called ``countries_trust.csv``: https://drive.google.com/drive/folders/1QnHTDQ0tb8_Ex6dMgNCwqJuL3PxzEKIv?usp=sharing

Import the dataset and assign it to a variable (e.g. ``df``). If you work with Colab, you will first have to copy the file to your Google Drive and then mount the drive (see Tutorial)!

If you didn't succeed in loading the data from Google Drive, you can also load the data from the following URL: ``"http://farys.org/daten/countries_trust.csv"``

**1.3.** Inspect the head and the tail of the dataset.

Now, print out summary statistics for the entire dataset.

Print the dataypes of the columns.

### Repetition: Indexing and filtering

**1.4.** Print out the following:
* First observation of the last column
* Population and GNI for the first 5 observations
* All observations with population lower than 30000
* Country name and population for all observations in continent "Oceania".

### Data cleaning

**1.5.** Now clean the column indices doing the following:


*   Replace the very long column names with shorter ones (e.g. ``top10_share``, ``homicide``, ``trust``, ``life_satisfaction``).
*   Convert all column names to lowercase

**1.6.** Set the ``country_code`` column as the index.

**1.7.** Drop the redundant column(s).

**1.8.** Print the minimum, the average, and the maximum value for the homicide variable (percentage of violent deaths among all deaths). How do you interpret these results?

**1.9.** Can you sort the data to find out what country has (a) the lowest and (b) the highest share of homicides? <font color='violet'> Hint: <font color='white'> The sort_values function has a parameter that allows you to specify whether the data should be sorted in descending or in ascending order.

**1.10.** Take a look at the categories of the ``continent`` column  and try to clean this column. How many observations do we have for each continent?

**1.11.** Find out how missing values in the ``top10_share`` variable were coded and convert them to proper missings. Recast the variable to a float so you can compute the top 10 income share of the median country.

Drop columns and rows with nothing but missing values.

Can you print the share of missing values for each variable/column?

**1.12.** Now try to create a dataset called ``trust_df`` that contains only those observations where the trust value is not missing.

**1.13.** Add a new variable (to the main dataset, not to ``trust_df``) called ``gni_per_capita`` with the per capita gross national income.

**1.14.** Export the cleaned dataset as a csv-file to your computer or your Google Drive.

## 2. Advanced exercises

**2.1.** Now add a column called ``inequality``. Its values should be either "low" or "high" depending on whether the top 10 income share of the country is above or below ``28.8`` (the median). Try to solve the task by writting a function that you can then use in ``apply()``. In your function, make sure that missing inequality values are handled correctly!

Can you find an easier way to do this (i.e. to cut a variable at the median)? Finding the right function, it can be done in one line of code! <font color='violet'> Hint: <font color='white'>Search for something like "make quantiles pandas"!

**2.2.** Create a column ``log_gni_pc`` with the log of the per capita gross national income.

**2.3.** Suppose you have some duplicate values in your dataset. Run the following code to create them:

In [ ]:
new_df = pd.DataFrame(np.repeat(df.values, 2, axis=0))
new_df.columns = df.columns
new_df.head()

Can you find a method or function that allows you to get rid of the duplicates in ``new_df``?

**2.4.** You may also encounter a different type of duplicates. Run the following code to create them:

In [ ]:
NA_df = df.copy().reset_index()
NA_df.loc[:,"population":] = np.NaN
new_df = new_df.append(NA_df)
new_df.sort_values("country_name", inplace=True)
new_df.head(6)

The repeated observations are only duplicates with respect to the country name (and NaN in all other variables). Can you find a way to delete them (making sure that the observations with the NaNs are deleted)?